import axios from 'axios';
import { NextResponse } from 'next/server';
import sgMail from '@sendgrid/mail';
import { projectsData } from '@/utils/data/projects-data';

// Use SendGrid to send emails. Set SENDGRID_API_KEY and EMAIL_ADDRESS in your .env file.
if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

// Helper function to send a message via Telegram (kept commented)
/*
async function sendTelegramMessage(token, chat_id, message) {
  const url = `https://api.telegram.org/bot${token}/sendMessage`;
  try {
    const res = await axios.post(url, {
      text: message,
      chat_id,
    });
    return res.data.ok;
  } catch (error) {
    console.error('Error sending Telegram message:', error.response?.data || error.message);
    return false;
  }
};
*/

// HTML email template with project and meta information
const generateEmailTemplate = (name, email, userMessage, meta = {}) => {
  const { timestamp, origin, env } = meta;
  const projectList = (projectsData || []).map(p => `- ${p.name}`).join('<br/>');

  return `
  <div style="font-family: Arial, sans-serif; color: #333; padding: 20px; background-color: #f4f4f4;">
    <div style="max-width: 700px; margin: auto; background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);">
      <h2 style="color: #007BFF; margin-bottom: 8px;">New Contact via Portfolio</h2>
      <p style="margin:4px 0;"><strong>Sender:</strong> ${name} &lt;${email}&gt;</p>
      <p style="margin:4px 0;"><strong>Message:</strong></p>
      <blockquote style="border-left: 4px solid #007BFF; padding-left: 10px; margin:8px 0; background:#fbfbff;">${userMessage}</blockquote>

      <hr style="border:none; border-top:1px solid #eee; margin:16px 0;"/>

      <h3 style="margin-bottom:8px;">Project snapshot (from repo)</h3>
      <p style="margin:0 0 8px 0; font-size:13px; color:#555;">Total projects: <strong>${(projectsData || []).length}</strong></p>
      <div style="font-size:13px; color:#555; margin-bottom:12px;">${projectList}</div>

      <h4 style="margin-bottom:8px;">Meta</h4>
      <p style="font-size:12px; color:#666; margin:0 0 4px 0;"><strong>Time:</strong> ${timestamp || ''}</p>
      <p style="font-size:12px; color:#666; margin:0 0 4px 0;"><strong>Origin:</strong> ${origin || 'unknown'}</p>
      <p style="font-size:12px; color:#666; margin:0 0 4px 0;"><strong>Environment:</strong> ${env || process.env.NODE_ENV || 'unknown'}</p>

      <p style="font-size:11px; color:#999; margin-top:16px;">This message was generated by your developer-portfolio Next.js app.</p>
    </div>
  </div>
`;
};

// Helper function to send an email using SendGrid
async function sendEmail(payload, message, meta = {}) {
  const { name, email, message: userMessage } = payload;

  if (!process.env.SENDGRID_API_KEY || !process.env.EMAIL_ADDRESS) {
    console.error('Missing SENDGRID_API_KEY or EMAIL_ADDRESS env variables');
    return false;
  }

  const subject = `Portfolio Contact — ${name} <${email}>`;
  const plainText = `${message}\n\nTime: ${meta.timestamp || new Date().toISOString()}\nOrigin: ${meta.origin || 'unknown'}\nEnvironment: ${meta.env || process.env.NODE_ENV}\nProjects: ${(projectsData || []).map(p => p.name).join(', ')}`;

  const msg = {
    to: process.env.EMAIL_ADDRESS,
    from: process.env.EMAIL_ADDRESS,
    subject,
    text: plainText,
    html: generateEmailTemplate(name, email, userMessage, meta),
    replyTo: email,
    headers: {
      'X-App-Env': process.env.NODE_ENV || 'development',
    },
  };

  try {
    await sgMail.send(msg);
    return true;
  } catch (error) {
    console.error('SendGrid error:', error?.response?.body || error.message || error);
    return false;
  }
}

export async function POST(request) {
  try {
    const payload = await request.json();
    const { name, email, message: userMessage } = payload;

    // Validate required env for SendGrid
    if (!process.env.SENDGRID_API_KEY || !process.env.EMAIL_ADDRESS) {
      return NextResponse.json({
        success: false,
        message: 'Email service not configured. Set SENDGRID_API_KEY and EMAIL_ADDRESS in .env',
      }, { status: 500 });
    }

    const origin = request.headers.get('x-forwarded-host') || request.headers.get('host') || process.env.NEXT_PUBLIC_APP_URL || 'http://localhost';
    const timestamp = new Date().toLocaleString();
    const meta = { timestamp, origin, env: process.env.NODE_ENV };

    const message = `New message from ${name}\n\nEmail: ${email}\n\nMessage:\n\n${userMessage}\n\n`;

    // Send email via SendGrid with meta
    const emailSuccess = await sendEmail(payload, message, meta);

    if (emailSuccess) {
      return NextResponse.json({
        success: true,
        message: 'Email sent successfully!',
      }, { status: 200 });
    }

    return NextResponse.json({
      success: false,
      message: 'Failed to send email. Check server logs for details.',
    }, { status: 500 });
  } catch (error) {
    console.error('API Error:', error.message);
    return NextResponse.json({
      success: false,
      message: 'Server error occurred.',
    }, { status: 500 });
  }
};